Repository YAPP-Github/20th-iOS-Team-1-BE, pull requests merged in 2022-08, with the labels that each got.

#164 hotfix: OSIV off로 인해 변경감지를 사용하지 않고, 직접 save() 사용
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
Labels: fix

#166 Test/165 comment unit and integration test
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
  src/main/java/com/yapp/pet/global/exception/comment/NotDeleteCommentException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/web/comment/model/CommentRequest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentServiceTest.java
  src/test/java/com/yapp/pet/support/AbstractIntegrationTest.java
Labels: refactor, test

#168 Test/167 pet 관련 unit integration test
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/global/exception/pet/NotFoundPetException.java
  src/main/java/com/yapp/pet/web/pet/model/PetRequest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceTest.java
Labels: refactor, test

#170 분산락(Distributed Lock) 적용
  build.gradle
  src/main/java/com/yapp/pet/domain/club/service/ClubParticipationService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/config/RedissonConfig.java
  src/main/java/com/yapp/pet/global/exception/club/FailureGetLockException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/test/java/com/yapp/pet/domain/club/ClubParticipationConcurrencyTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/resources/config/application.yml
Labels: refactor

#172 fix: 애플로그인 로직 수정
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/token/entity/Token.java
Labels: fix

#173 배포 #148(분산락) #171(애플로그인 이슈)
  build.gradle
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubParticipationService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/token/entity/Token.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/config/RedissonConfig.java
  src/main/java/com/yapp/pet/global/exception/club/FailureGetLockException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/test/java/com/yapp/pet/domain/club/ClubParticipationConcurrencyTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: fix, refactor

#176 fix: 회원탈퇴시 토큰 삭제
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
Labels: fix

#177 fix: OSIV off 옵션으로 인한 오류 수정
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
Labels: fix

#178 fix: 이미지 저장 이슈 해결
  src/main/java/com/yapp/pet/domain/account/event/AccountEventHandler.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
Labels: fix

#179 Feat/147 test containers 이용하여 통합 테스트 구성
  .github/workflows/deploy.yaml
  build.gradle
  docker-compose.yml
  spy.log
  src/test/java/com/yapp/pet/PetApplicationTests.java
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubParticipationConcurrencyTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/pet_image/PetImageServiceTest.java
  src/test/java/com/yapp/pet/domain/token/TokenServiceIntegrationTest.java
  src/test/java/com/yapp/pet/global/jwt/JwtServiceTest.java
  src/test/java/com/yapp/pet/support/AbstractIntegrationTest.java
  src/test/resources/config/application-test.yml
  src/test/resources/sql/clean-up.sql
  src/test/resources/sql/data.sql
  src/test/resources/sql/schema.sql
Labels: feat, refactor, test

#182 fix: 모임 참여 조건 만족하지 못하는 경우에도, es update로 인한 500 에러 해결
  src/main/java/com/yapp/pet/web/club/ClubController.java
Labels: fix

#183 Refactor/181 테스트 생성자 주입으로 변경
  build.gradle
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubParticipationConcurrencyTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/comment/service/CommentServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceIntegrationTest.java
  src/test/java/com/yapp/pet/domain/pet_image/PetImageServiceTest.java
  src/test/java/com/yapp/pet/domain/token/TokenServiceIntegrationTest.java
  src/test/java/com/yapp/pet/global/jwt/JwtServiceTest.java
  src/test/java/com/yapp/pet/support/AbstractIntegrationTest.java
Labels: refactor

#184 DB Replication을 통한 read/write DB 분리
  src/main/java/com/yapp/pet/global/config/routing/DataSourceConfiguration.java
  src/main/java/com/yapp/pet/global/config/routing/RoutingDataSource.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
Labels: refactor, Performance

#188 Fix/186 범위 내에 있는 모임 조회 시 참여 가능한 모임만 조회
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClubRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
Labels: bug, fix
