Repository YAPP-Github/20th-iOS-Team-1-BE, pull requests merged in 2022-06, with the labels that each got.

#22 Feature/18 session 의존성 제거
  src/main/java/com/yapp/pet/domain/account/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/AccountService.java
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/token/entity/Token.java
  src/main/java/com/yapp/pet/domain/token/repository/TokenRepositoryImpl.java
  src/main/java/com/yapp/pet/global/annotation/AuthAccount.java
  src/main/java/com/yapp/pet/global/annotation/AuthAccountResolver.java
  src/main/java/com/yapp/pet/global/config/SecurityConfig.java
  src/main/java/com/yapp/pet/global/config/WebConfig.java
  src/main/java/com/yapp/pet/global/exception/Account/AccountNotFoundException.java
  src/main/java/com/yapp/pet/global/jwt/ExceptionHandlerFilter.java
  src/main/java/com/yapp/pet/global/jwt/JwtAuthentication.java
  src/main/java/com/yapp/pet/global/jwt/JwtFilter.java
  src/main/java/com/yapp/pet/global/jwt/JwtService.java
  src/main/java/com/yapp/pet/global/util/JwtUtils.java
  src/main/java/com/yapp/pet/web/HealthController.java
  src/main/java/com/yapp/pet/web/token/TokenController.java
  src/test/java/com/yapp/pet/global/jwt/JwtServiceTest.java
Labels: feat, entity

#27 Feature/13 필터로 모임 조회
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/common/PetSizeType.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
Labels: feat

#28 Develop
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/common/PetSizeType.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
Labels: feat

#30 Feature/29 스케줄러 club 종료 api 추가
  src/main/java/com/yapp/pet/PetApplication.java
  src/main/java/com/yapp/pet/domain/accountclub/entity/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
Labels: feat

#31 Develop
  src/main/java/com/yapp/pet/PetApplication.java
  src/main/java/com/yapp/pet/domain/accountclub/entity/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
Labels: feat

#39 배포 - #25 회원가입 API 구현
  build.gradle
  src/main/java/com/yapp/pet/domain/account/AccountService.java
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImage.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageRepository.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/annotation/AuthAccountResolver.java
  src/main/java/com/yapp/pet/global/exception/account/AccountNotFoundException.java
  src/main/java/com/yapp/pet/global/util/s3/S3Properties.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/HealthController.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/mapper/AccountMapper.java
  src/main/java/com/yapp/pet/web/account/model/AccountSignUpRequest.java
  src/main/java/com/yapp/pet/web/account/model/AccountValidationResponse.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/resources/assets/cat.jpg
  src/test/resources/assets/city.jpg
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: feat

#41 Feature/40 dummy data 추가에 따른 테스트 변경
  src/main/java/com/yapp/pet/domain/club/entity/Category.java
  src/main/java/com/yapp/pet/domain/club/entity/EligibleSex.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: refactor, test

#42 Develop
  src/main/java/com/yapp/pet/domain/club/entity/Category.java
  src/main/java/com/yapp/pet/domain/club/entity/EligibleSex.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: refactor, test

#43 Feature/36 범위 내 모임 조회
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: feat

#44 Develop
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: feat

#46 Feature/35 마이페이지 조회와, 엔티티 연관관계 수정
  src/main/java/com/yapp/pet/domain/account/AccountService.java
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImage.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/domain/account_tag/AccountTag.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepository.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImage.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTag.java
  src/main/java/com/yapp/pet/global/mapper/AccountMapper.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: feat, entity

#48 배포 - #35 엔티티 연관관계 수정, 마이페이지 조회 API 개발
  src/main/java/com/yapp/pet/domain/account/AccountService.java
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImage.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/domain/account_tag/AccountTag.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepository.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImage.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTag.java
  src/main/java/com/yapp/pet/global/mapper/AccountMapper.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: feat, entity

#51 Fix/49 유저의 관심 태그 엔티티 삭제 , 카테고리로 변경
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account_tag/AccountTag.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/common/Category.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: entity

#52 배포 - #49 유저의 관심 태그 엔티티 삭제 , 카테고리로 변경
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account_tag/AccountTag.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/common/Category.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: entity

#53 Feature/45 지도에서 fin 클릭 시 해당 모임 조회
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingSimpleClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
Labels: feat

#54 Develop
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingSimpleClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
Labels: feat

#55 Feature/47 유저 정보수정 api 개발
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImage.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/token/TokenService.java
  src/main/java/com/yapp/pet/domain/token/repository/TokenRepositoryImpl.java
  src/main/java/com/yapp/pet/global/mapper/AccountMapper.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/model/AccountUpdateRequest.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/resources/config/application.yml
  src/test/resources/data.sql
Labels: feat

#58 Refactor/57 club entity 수정에 따른 코드 변경
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/entity/EligibleBreed.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/util/DistanceUtil.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingSimpleClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: refactor

#60 Develop
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/ClubService.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/entity/EligibleBreed.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/util/DistanceUtil.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingSimpleClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/resources/data.sql
Labels: refactor

#62 Fix/61 마이페이지 조회기능 수정
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/resources/data.sql
Labels: fix, refactor

#63 배포 - 마이페이지 조회 API 수정
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/resources/data.sql
Labels: fix, refactor

#66 Feature/59 강아지 추가 탭 api 추가
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImage.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageRepository.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageService.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTag.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagRepository.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagService.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/pet/PetController.java
  src/main/java/com/yapp/pet/web/pet/model/PetRequest.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceTest.java
  src/test/java/com/yapp/pet/domain/pet_image/PetImageServiceTest.java
  src/test/resources/data.sql
Labels: feat

#67 Develop
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImage.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageRepository.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageService.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTag.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagRepository.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagService.java
  src/main/java/com/yapp/pet/global/TogaetherConstants.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/pet/PetController.java
  src/main/java/com/yapp/pet/web/pet/model/PetRequest.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceTest.java
  src/test/java/com/yapp/pet/domain/pet_image/PetImageServiceTest.java
  src/test/resources/data.sql
Labels: feat

#69 Develop
  src/main/java/com/yapp/pet/domain/pet/entity/Pet.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepository.java
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/global/mapper/PetMapper.java
  src/main/java/com/yapp/pet/web/pet/PetController.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/pet/service/PetServiceTest.java
  src/test/java/com/yapp/pet/domain/pet_image/PetImageServiceTest.java
Labels: feat

#80 Develop
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
Labels: refactor

#83 fix: 코드 복구
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/test/resources/data.sql
Labels: bug, fix

#84 코드 복구 배포
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepositoryImpl.java
  src/test/resources/data.sql
Labels: bug, fix

#85 Feature/76 댓글 생성 api 추가
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/comment/Comment.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentRequest.java
  src/main/resources/static/openapi.yml
Labels: feat

#87 Develop
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/comment/Comment.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentRequest.java
  src/main/resources/static/openapi.yml
Labels: feat

#88 Feature/77 댓글 삭제 api 추가
  src/main/java/com/yapp/pet/domain/comment/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/resources/static/openapi.yml
Labels: feat

#89 Develop
  src/main/java/com/yapp/pet/domain/comment/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/resources/static/openapi.yml
Labels: feat

#90 Feature/79 댓글 조회 api 추가
  src/main/java/com/yapp/pet/domain/comment/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentResponse.java
Labels: feat

#91 배포 - 댓글 조회 기능 추가
  src/main/java/com/yapp/pet/domain/comment/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentResponse.java
Labels: feat

#93 Fix/92 애플로그인 수정
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/apple/model/AppleRequest.java
  src/main/resources/static/openapi.yml
Labels: fix

#94 Feature/70 모임 목록 조회
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/repository/AccountRepository.java
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubFindCondition.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/global/annotation/AuthAccountResolver.java
  src/main/java/com/yapp/pet/global/exception/account/AccountNotFoundException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionHandlerController.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/global/exception/common/response/ExceptionResponse.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubFindResponse.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/resources/config/application-local.yaml
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/club/ClubServiceTest.java
  src/test/resources/data.sql
Labels: feat

#96 fix: 애플로그인 버그 수정
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/global/jwt/JwtService.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleClient.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/apple/model/ApplePublicKeyResponse.java
Labels: fix
