Repository YAPP-Github/20th-iOS-Team-1-BE, pull requests merged in 2022-07, with the labels that each got.

#97 Feature/71 모임상세조회
  src/main/java/com/yapp/pet/domain/club/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubFindDetailResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/ClubQueryServiceTest.java
  src/test/resources/data.sql
Labels: feat

#98 Feature/72 모임 생성 api 추가
  src/main/java/com/yapp/pet/domain/accountclub/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/global/exception/club/NotHaveAnyPetException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubCreateRequest.java
  src/main/resources/static/openapi.yml
Labels: feat

#99 Feature/73 모임참여 나가기 삭제
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/global/exception/club/NotLeaderException.java
  src/main/java/com/yapp/pet/global/exception/common/ExceptionStatus.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubParticipateRejectReason.java
  src/main/java/com/yapp/pet/web/club/model/ClubParticipateResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/resources/data.sql
Labels: feat

#105 Feature/100 elasticsearch 추가
  build.gradle
  src/main/java/com/yapp/pet/domain/club/document/AccountClubDocument.java
  src/main/java/com/yapp/pet/domain/club/document/ClubDocument.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubSearchRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/CustomClubSearchRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/CustomClubSearchRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/global/config/ElasticSearchConfig.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/resources/config/application-local.yaml
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
Labels: feat, Performance

#112 Fix/109 마이페이지 조회 수정
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
Labels: feature fix

#113 Develop
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
Labels: feature fix

#115 Refactor/111 elasticsearch local develop 환경 분리하기
  .github/workflows/deploy.yaml
  src/main/java/com/yapp/pet/global/config/ElasticSearchConfig.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
Labels: refactor

#117 Fix/102 custom cursor
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/resources/data.sql
Labels: refactor

#118 커스텀 curosr 구현 배포
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/resources/data.sql
Labels: refactor

#119 Fix/103 순환참조 이슈
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/global/jwt/JwtService.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/resources/config/application.yml
Labels: fix

#121 Fix/120 add email
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/apple/model/AppleRequest.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/java/com/yapp/pet/web/oauth/kakao/model/KakaoTokenResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/token/TokenServiceTest.java
Labels: feature fix

#122 배포 - 순환참조 이슈 해결, 회원 정보에 이메일 추가
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/global/jwt/JwtService.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/apple/model/AppleRequest.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/java/com/yapp/pet/web/oauth/kakao/model/KakaoTokenResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/account/AccountServiceTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/token/TokenServiceTest.java
  src/test/resources/config/application.yml
Labels: fix, feature fix

#123 Feature/114 회원 탈퇴 api 추가
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClubRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentRepository.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/domain/pet/repository/PetRepository.java
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagRepository.java
  src/main/java/com/yapp/pet/domain/pet_tag/PetTagService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/resources/static/openapi.yml
Labels: feat

#126 Refactor/125 모임 검색 api refactoring
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
Labels: refactor

#128 AWS S3와 강결합 문제 해결
  src/main/java/com/yapp/pet/PetApplication.java
  src/main/java/com/yapp/pet/domain/account/event/SignedUpEvent.java
  src/main/java/com/yapp/pet/domain/account/event/SignedUpEventHandler.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/domain/common/EventType.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageService.java
  src/main/java/com/yapp/pet/global/config/AsyncThreadConfiguration.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
Labels: refactor

#130 fix: 회원정보 수정 시, 주소값 null 여부 검사 수정
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/entity/Address.java
Labels: bug

#131 배포 - #129 #104 #125
  src/main/java/com/yapp/pet/PetApplication.java
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/entity/Address.java
  src/main/java/com/yapp/pet/domain/account/event/SignedUpEvent.java
  src/main/java/com/yapp/pet/domain/account/event/SignedUpEventHandler.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/account_image/AccountImageService.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/common/EventType.java
  src/main/java/com/yapp/pet/domain/pet_image/PetImageService.java
  src/main/java/com/yapp/pet/global/config/AsyncThreadConfiguration.java
  src/main/java/com/yapp/pet/global/util/s3/S3Utils.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/SearchingClubDto.java
  src/main/java/com/yapp/pet/web/club/model/SearchingWithinRangeClubDto.java
Labels: bug, refactor

#134 Fix/133 add return value
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/comment/CommentService.java
  src/main/java/com/yapp/pet/domain/pet/service/PetService.java
  src/main/java/com/yapp/pet/domain/token/TokenService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/pet/PetController.java
  src/main/java/com/yapp/pet/web/token/TokenController.java
  src/main/resources/static/openapi.yml
Labels: bug

#136 perf: index 생성
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
Labels: Performance

#140 Refactor/139 모임참여 조건 추가
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubValidator.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubParticipateRejectReason.java
  src/main/java/com/yapp/pet/web/club/model/ClubParticipateResponse.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
  src/test/resources/data.sql
Labels: refactor, feature fix

#142 Fix/141 fix response
  src/main/java/com/yapp/pet/domain/comment/service/CommentQueryService.java
  src/main/java/com/yapp/pet/web/account/model/MyPageResponse.java
  src/main/java/com/yapp/pet/web/club/model/ClubFindDetailResponse.java
  src/main/java/com/yapp/pet/web/comment/model/CommentResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/resources/data.sql
Labels: fix

#145 코드 리뷰 반영 (리팩토링)
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/account/event/AccountDeletedEvent.java
  src/main/java/com/yapp/pet/domain/account/event/AccountEventHandler.java
  src/main/java/com/yapp/pet/domain/account/event/SavedImageEvent.java
  src/main/java/com/yapp/pet/domain/account/service/AccountQueryService.java
  src/main/java/com/yapp/pet/domain/account/service/AccountService.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClub.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/event/ClubDeletedEvent.java
  src/main/java/com/yapp/pet/domain/club/event/ClubEventHandler.java
  src/main/java/com/yapp/pet/domain/club/repository/elasticsearch/ClubSearchRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/elasticsearch/CustomClubSearchRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/elasticsearch/CustomClubSearchRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/club/service/ClubValidator.java
  src/main/java/com/yapp/pet/domain/comment/event/CommentDeletedEvent.java
  src/main/java/com/yapp/pet/domain/comment/event/CommentEventHandler.java
  src/main/java/com/yapp/pet/domain/common/EventType.java
  src/main/java/com/yapp/pet/domain/report/Report.java
  src/main/java/com/yapp/pet/domain/report/ReportService.java
  src/main/java/com/yapp/pet/global/annotation/AuthAccountResolver.java
  src/main/java/com/yapp/pet/global/config/ElasticSearchConfig.java
  src/main/java/com/yapp/pet/global/mapper/AccountMapper.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/club/ClubController.java
  src/main/java/com/yapp/pet/web/club/model/ClubCreateRequest.java
  src/main/java/com/yapp/pet/web/club/model/ClubFindByConditionRequest.java
  src/main/java/com/yapp/pet/web/oauth/apple/AppleController.java
  src/main/java/com/yapp/pet/web/oauth/kakao/KakaoController.java
  src/main/java/com/yapp/pet/web/report/ReportController.java
  src/main/java/com/yapp/pet/web/token/TokenController.java
  src/main/resources/config/application-dev.yaml
  src/main/resources/config/application-local.yaml
  src/test/java/com/yapp/pet/domain/club/repository/ClubRepositoryImplTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
  src/test/java/com/yapp/pet/domain/club/service/ClubServiceTest.java
Labels: refactor

#146 모임참여 동시성 문제 해결 v1
  src/main/java/com/yapp/pet/domain/accountclub/AccountClub.java
  src/main/java/com/yapp/pet/domain/accountclub/AccountClubRepository.java
  src/main/java/com/yapp/pet/domain/club/entity/Club.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepositoryCustom.java
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepositoryImpl.java
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/test/java/com/yapp/pet/domain/club/ClubParticipationConcurrencyTest.java
  src/test/resources/concurrencyTestData.sql
  src/test/resources/data.sql
Labels: fix, refactor

#152 배포 - 버그 수정
  src/main/java/com/yapp/pet/domain/token/repository/TokenRepositoryImpl.java
  src/main/java/com/yapp/pet/web/club/model/ClubFindDetailResponse.java
Labels: fix

#153 Fix/151 댓글 조회 시 NPE 처리
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceTest.java
Labels: bug, fix

#154 Develop
  src/main/java/com/yapp/pet/domain/account/entity/Account.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
  src/main/java/com/yapp/pet/web/account/AccountController.java
  src/main/java/com/yapp/pet/web/comment/CommentController.java
  src/main/java/com/yapp/pet/web/comment/model/CommentResponse.java
  src/main/resources/static/openapi.yml
  src/test/java/com/yapp/pet/domain/comment/service/CommentQueryServiceTest.java
Labels: bug

#157 #155 코드 리뷰 리팩토링
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
Labels: refactor

#159 #155 모임 종료 상태로 변경하는 스케줄러 버그 해결
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
Labels: fix

#160 배포 #155 #158
  src/main/java/com/yapp/pet/domain/club/repository/jpa/ClubRepository.java
  src/main/java/com/yapp/pet/domain/club/scheduler/Scheduler.java
  src/main/java/com/yapp/pet/domain/club/service/ClubQueryService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentService.java
  src/test/java/com/yapp/pet/domain/club/service/ClubQueryServiceTest.java
Labels: fix, refactor

#162 Fix/161 댓글 조회 시 pet 없는 유저는 댓글이
  src/main/java/com/yapp/pet/domain/club/service/ClubService.java
  src/main/java/com/yapp/pet/domain/comment/service/CommentQueryService.java
  src/main/java/com/yapp/pet/global/mapper/ClubMapper.java
Labels: bug, fix
